#include <fstream>
#include <iostream>
#include <string>

using namespace std;

// The script generates the sets with different material properties of the structure based on the .ele file generated by tetgen(with regions labeled with 0-index)
int main (int argc, char *argv[])
{
   if (argc <= 1){
       cerr << "Must pass in path to configuration file!" << endl;
       return 1;
   }
   ifstream Infile(argv[1]);
   string FileName(argv[1]);
   FileName = FileName.substr(0,FileName.size()-4);
   int nRegion;
   cout << "Number of regions in the structure" << endl;
   cin >> nRegion;
   ofstream ofs[nRegion];  
   for(int i = 0; i < nRegion; i++){
       ofs[i].open(FileName + "_Set" + char('0'+i) + ".txt");
   } 
   int nEle, Element, Region;
   Infile >> nEle;
   Infile >> Element;
   Infile >> Element;
   int count[2]={0,0};
   for(int i =0; i < nEle; i++){
       Infile >> Element;
       Infile >> Region;
       Infile >> Region;
       Infile >> Region;
       Infile >> Region;
       Infile >> Region;
       count[Region]++;
       ofs[Region] << Element << ",";
       if(count[Region]%10 == 0 && count[Region] != 0){
          ofs[Region] << endl;
       }
   }

   return 0;
}
   

